spring:
  datasource-master:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    username: master
    password: master


tenant:
  tenant-datasource:
    database: test
    port: 5328
    host: localhost