spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    username: thomas
    password: thomas

liquibase:
  changeLog: classpath:/changelog/master/changelog-master.xml
  contexts: development
  url: jdbc:postgresql://localhost/test
  user: thomas
  password: thomas

