spring:
  datasource-master:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    username: master
    password: master
  jpa:
    hibernate:
      ddlAuto: none
liquibase:
  changeLog: classpath:/db/changelog.tenant/db.changelog.tenant-master.xml
  contexts: development
  url: jdbc:postgresql://localhost/test
  user: thomas
  password: thomas

tenant:
  tenant-datasource:
    database: test
    port: 5328
    host: localhost