spring:
  datasource-master:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test
    username: thomas
    password: thomas
  jpa:
    hibernate:
      ddlAuto: none
liquibase:
  changeLog: classpath:/db/changelog/db.changelog-master.xml
  contexts: development
  url: jdbc:postgresql://localhost/test
  user: thomas
  password: thomas

tenant:
  master:
    user: thomas
    password: thomas
    database: test
    port: 5328
    host: localhost