---
- hosts: all


  sudo: true
  tasks:

    - name: add postgres repository
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main' state=present
    - name: add repo key
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present validate_certs=no
    - name: update apt cache
      apt: update_cache=yes

    - name: install required packages
      apt: name={{ item }} state=present
      with_items:
        - python-psycopg2
        - postgresql-9.4
        - vim



    - name: copy postgresql config
      copy: src=config/postgresql.conf dest=/etc/postgresql/9.4/main/postgresql.conf owner=postgres group=postgres
    - name: copy postgresql hba config
      copy: src=config/pg_hba.conf dest=/etc/postgresql/9.4/main/pg_hba.conf owner=postgres group=postgres
    - name: restart postgresql
      service: name=postgresql state=restarted
    - name: create  postgres user
      postgresql_user: name=thomas password=thomas role_attr_flags=SUPERUSER
      sudo_user: postgres
    - name: create test db
      postgresql_db: name=test owner=thomas
      sudo_user: postgres

